services:
  qc.fair_scummy-khaki-termite:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.FAIR
      dockerfile: Dockerfile-fuji
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
